#
# Makefile for bachelor thesis
#

# %.pdf : %.tex_
# 	pdflatex $<

%.pdf : %.tex
	pdflatex $<
	pdflatex $<

%.dvi : %.tex_
	latex $<

%.ps : %.dvi
	dvips $<

# %.tex_ : %.tex
# 	vlna -f -l -v KkSsVvZzOoUuAaIi $< $@

bajer13model_presentation.pdf:

# ga-rbf_ideal2010.pdf:
#
# dp-defend.pdf:
#
# all: dp-defend.pdf dp-defend_9min.pdf dp-defend_8min.pdf dp-defend_11min.pdf dp-defend_12min.pdf
#
# dp-defend.ps:
#
# dp-defend.dvi:

